#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
ALLOW_MUTATING_WATCH_SOAK="${ALLOW_MUTATING_WATCH_SOAK:-false}"
ENDPOINT="${ENDPOINT:-127.0.0.1:3379}"
WATCHERS="${WATCHERS:-25}"
EVENTS="${EVENTS:-50}"
TIMEOUT_SECONDS="${TIMEOUT_SECONDS:-60}"
CLEANUP_TIMEOUT_SECONDS="${CLEANUP_TIMEOUT_SECONDS:-300}"
WRITE_INTERVAL="${WRITE_INTERVAL:-0s}"
WRITE_CONCURRENCY="${WRITE_CONCURRENCY:-1}"
RUN_ID="${RUN_ID:-watch-soak-$(date +%s%N)}"
SLOW_CONSUMER="${SLOW_CONSUMER:-false}"
REQUIRE_SLOW_CONSUMER_OUTCOMES="${REQUIRE_SLOW_CONSUMER_OUTCOMES:-false}"
SLOW_CONSUMER_EXPECTED_OUTCOME="${SLOW_CONSUMER_EXPECTED_OUTCOME:-recovered}"
INFO_ENDPOINT="${INFO_ENDPOINT:-}"

if [[ "$ALLOW_MUTATING_WATCH_SOAK" != true && "$ALLOW_MUTATING_WATCH_SOAK" != false ]]; then
  echo "ALLOW_MUTATING_WATCH_SOAK must be true or false" >&2
  exit 2
fi
if [[ "$ALLOW_MUTATING_WATCH_SOAK" != true ]]; then
  echo "refusing shared-endpoint watch writes without ALLOW_MUTATING_WATCH_SOAK=true" >&2
  exit 1
fi
if ! command -v go >/dev/null 2>&1; then
  echo "missing required command: go" >&2
  exit 1
fi

cd "$ROOT_DIR"
exec env \
  ENDPOINT="$ENDPOINT" \
  WATCHERS="$WATCHERS" \
  EVENTS="$EVENTS" \
  TIMEOUT_SECONDS="$TIMEOUT_SECONDS" \
  CLEANUP_TIMEOUT_SECONDS="$CLEANUP_TIMEOUT_SECONDS" \
  WRITE_INTERVAL="$WRITE_INTERVAL" \
  WRITE_CONCURRENCY="$WRITE_CONCURRENCY" \
  RUN_ID="$RUN_ID" \
  SLOW_CONSUMER="$SLOW_CONSUMER" \
  REQUIRE_SLOW_CONSUMER_OUTCOMES="$REQUIRE_SLOW_CONSUMER_OUTCOMES" \
  SLOW_CONSUMER_EXPECTED_OUTCOME="$SLOW_CONSUMER_EXPECTED_OUTCOME" \
  INFO_ENDPOINT="$INFO_ENDPOINT" \
  go run ./hack/dev/cmd/watch-soak
