apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubebrain-tikv-transaction-recovery
  namespace: kubebrain-system
rules:
  - apiGroups: [apps]
    resources: [statefulsets]
    resourceNames: [kubebrain]
    verbs: [get, watch]
  - apiGroups: [apps]
    resources: [statefulsets/scale]
    resourceNames: [kubebrain]
    verbs: [get, patch, update]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubebrain-tikv-transaction-recovery
  namespace: kubebrain-system
subjects:
  - kind: ServiceAccount
    name: kubebrain-tikv-transaction-recovery-executor
    namespace: kubebrain-operations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubebrain-tikv-transaction-recovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubebrain-tikv-transaction-recovery
  namespace: tidb-cluster
rules:
  - apiGroups: [pingcap.com]
    resources: [tidbclusters]
    resourceNames: [kb]
    verbs: [get]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [create]
  - apiGroups: [""]
    resources: [services/proxy]
    resourceNames: ["http:kb-pd:2379"]
    verbs: [get]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    resourceNames: [pd-kb-pd-0, pd-kb-pd-1, pd-kb-pd-2, tikv-kb-tikv-0, tikv-kb-tikv-1, tikv-kb-tikv-2]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubebrain-tikv-transaction-recovery
  namespace: tidb-cluster
subjects:
  - kind: ServiceAccount
    name: kubebrain-tikv-transaction-recovery-executor
    namespace: kubebrain-operations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubebrain-tikv-transaction-recovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubebrain-tikv-transaction-recovery-pv-reader
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubebrain-tikv-transaction-recovery-pv-reader
subjects:
  - kind: ServiceAccount
    name: kubebrain-tikv-transaction-recovery-executor
    namespace: kubebrain-operations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubebrain-tikv-transaction-recovery-pv-reader
