apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: kubebrain-cold-physical-snapshot, namespace: kubebrain-system}
rules:
  - apiGroups: [apps]
    resources: [statefulsets]
    resourceNames: [kubebrain]
    verbs: [get, watch, patch]
  - apiGroups: [apps]
    resources: [statefulsets/scale]
    resourceNames: [kubebrain]
    verbs: [get, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: kubebrain-cold-physical-snapshot, namespace: kubebrain-system}
subjects:
  - {kind: ServiceAccount, name: kubebrain-cold-physical-snapshot-executor, namespace: kubebrain-operations}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: kubebrain-cold-physical-snapshot}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: kubebrain-cold-physical-snapshot, namespace: tidb-cluster}
rules:
  - apiGroups: [pingcap.com]
    resources: [tidbclusters]
    resourceNames: [kb]
    verbs: [get, patch]
  - apiGroups: [apps]
    resources: [statefulsets]
    resourceNames: [kb-pd, kb-tikv]
    verbs: [get, watch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list]
  - apiGroups: [snapshot.storage.k8s.io]
    resources: [volumesnapshots]
    verbs: [create, get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: kubebrain-cold-physical-snapshot, namespace: tidb-cluster}
subjects:
  - {kind: ServiceAccount, name: kubebrain-cold-physical-snapshot-executor, namespace: kubebrain-operations}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: kubebrain-cold-physical-snapshot}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: {name: kubebrain-cold-physical-snapshot-read-storage}
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get]
  - apiGroups: [snapshot.storage.k8s.io]
    resources: [volumesnapshotclasses, volumesnapshotcontents]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: kubebrain-cold-physical-snapshot-read-storage}
subjects:
  - {kind: ServiceAccount, name: kubebrain-cold-physical-snapshot-executor, namespace: kubebrain-operations}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: kubebrain-cold-physical-snapshot-read-storage}
