#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"; . "${ROOT_DIR}/hack/production/operation-time-validation.sh"
REQUEST_ID="${REQUEST_ID:-}"; INSTANCE="${INSTANCE:-}"; ENDPOINT="${ENDPOINT:-}"; PREFIX="${PREFIX:-/registry}"; BATCH_SIZE="${BATCH_SIZE:-1000}"; WORK_DIR="${WORK_DIR:-/var/lib/kubebrain-operation}"
OBJECT_STORE_ID="${OBJECT_STORE_ID:-}"; S3_ENDPOINT="${S3_ENDPOINT:-}"; S3_BUCKET="${S3_BUCKET:-}"; S3_OBJECT_KEY="${S3_OBJECT_KEY:-}"; S3_FORCE_PATH_STYLE="${S3_FORCE_PATH_STYLE:-false}"; AWS_REGION="${AWS_REGION:-}"; RETENTION_MODE="${RETENTION_MODE:-COMPLIANCE}"; RETAIN_UNTIL_UNIX="${RETAIN_UNTIL_UNIX:-}"; MIN_RECORDS="${MIN_RECORDS:-1}"; MAX_AGE_SECONDS="${MAX_AGE_SECONDS:-3600}"
OPERATION_NAMESPACE="${OPERATION_NAMESPACE:-kubebrain-operations}"; KUBE_CONTEXT="${KUBE_CONTEXT:-}"; KUBECTL="${KUBECTL:-kubectl}"; OPERATIONCTL="${OPERATIONCTL:-kubebrain-operationctl}"; JQ="${JQ:-jq}"; MAX_OPERATION_PARAMETERS_BYTES=65536; MAX_EXISTING_SECRET_RESPONSE_BYTES=87389
die(){ echo "$*" >&2; exit 1; }; resolve(){ if [[ "$1" == */* ]]; then [[ -x "$1" ]]||return 1; printf %s "$1"; else command -v "$1"; fi; }
id='^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'; [[ "$REQUEST_ID" =~ ^[a-z0-9]([-a-z0-9.]{0,126}[a-z0-9])?$ && "$INSTANCE" =~ $id ]] || die "backup request identity is invalid"
[[ -n "$ENDPOINT" && "$PREFIX" == /* && -n "$OBJECT_STORE_ID" && -n "$S3_ENDPOINT" && -n "$S3_BUCKET" && -n "$S3_OBJECT_KEY" && -n "$AWS_REGION" ]] || die "backup endpoint and object identity are required"
[[ "$ENDPOINT" != *[[:cntrl:]]* && "$ENDPOINT" != *\"* && "$ENDPOINT" != *\\* && "$S3_ENDPOINT" != *[[:cntrl:]]* && "$S3_ENDPOINT" != *\"* && "$S3_ENDPOINT" != *\\* ]] || die "backup endpoint identity is unsafe"
for scope in "$OBJECT_STORE_ID" "$S3_BUCKET" "$S3_OBJECT_KEY"; do [[ ! "$scope" =~ [[:space:]] ]] || die "backup object identity is unsafe"; done
[[ "$S3_OBJECT_KEY" != /* && "$S3_OBJECT_KEY" != . && "$S3_OBJECT_KEY" != .. && "$S3_OBJECT_KEY" != *"//"* && "$S3_OBJECT_KEY" != *"/../"* && "$S3_OBJECT_KEY" != *"/./"* && "$S3_OBJECT_KEY" != */. && "$S3_OBJECT_KEY" != */.. ]] || die "backup object identity is unsafe"
operation_is_positive_int64 "$BATCH_SIZE" && operation_is_positive_int64 "$RETAIN_UNTIL_UNIX" && operation_is_nonnegative_int64 "$MIN_RECORDS" && operation_is_positive_int64 "$MAX_AGE_SECONDS" || die "backup numeric bounds are invalid"
[[ "$S3_FORCE_PATH_STYLE" == true || "$S3_FORCE_PATH_STYLE" == false ]] && [[ "$RETENTION_MODE" == COMPLIANCE || "$RETENTION_MODE" == GOVERNANCE ]] || die "backup boolean or retention mode is invalid"
command -v realpath >/dev/null || die "realpath is required"
[[ "$OPERATION_NAMESPACE" == kubebrain-operations && -n "$KUBE_CONTEXT" && "$WORK_DIR" == /* && -d "$WORK_DIR" && ! -L "$WORK_DIR" && "$(realpath -e -- "$WORK_DIR")" == "$WORK_DIR" ]] || die "production namespace, context, and canonical workspace are required"
KUBECTL="$(resolve "$KUBECTL")"||die "KUBECTL must be executable"; OPERATIONCTL="$(resolve "$OPERATIONCTL")"||die "OPERATIONCTL must be executable"; JQ="$(resolve "$JQ")"||die "JQ must be executable"
hash="$(printf '%s\n' "$REQUEST_ID" "$INSTANCE" "$ENDPOINT" "$PREFIX" "$OBJECT_STORE_ID" "$S3_BUCKET" "$S3_OBJECT_KEY" "$RETAIN_UNTIL_UNIX" | sha256sum | cut -c1-20)"; name="backup-${hash}"; secret="${name}-parameters"; artifact="${WORK_DIR}/${name}.jsonl"; metrics="${WORK_DIR}/${name}.metrics"; receipt="${WORK_DIR}/${name}.receipt.json"
temp="$(mktemp -d)"; trap 'rm -rf -- "$temp"' EXIT; params="$temp/parameters.json"
"$JQ" -cnS --arg endpoint "$ENDPOINT" --arg prefix "$PREFIX" --arg artifact "$artifact" --arg metrics "$metrics" --arg backup "$name" --arg store "$OBJECT_STORE_ID" --arg s3 "$S3_ENDPOINT" --arg bucket "$S3_BUCKET" --arg key "$S3_OBJECT_KEY" --arg region "$AWS_REGION" --arg retention "$RETENTION_MODE" --arg receipt "$receipt" --argjson batch "$BATCH_SIZE" --argjson path "$S3_FORCE_PATH_STYLE" --argjson retain "$RETAIN_UNTIL_UNIX" --argjson records "$MIN_RECORDS" --argjson age "$MAX_AGE_SECONDS" '{endpoint:$endpoint,prefix:$prefix,artifact_output:$artifact,batch_size:$batch,metrics_output:$metrics,backup_id:$backup,object_store_id:$store,s3_endpoint:$s3,s3_bucket:$bucket,s3_object_key:$key,s3_force_path_style:$path,aws_region:$region,retention_mode:$retention,retain_until_unix:$retain,min_records:$records,max_age_seconds:$age,receipt_output:$receipt}' >"$params"
[[ "$(wc -c <"$params")" -le "$MAX_OPERATION_PARAMETERS_BYTES" ]] || die "backup parameters exceed 65536 bytes"
sha="$(sha256sum "$params"|cut -d ' ' -f1)"; context=(); [[ "$KUBE_CONTEXT" == in-cluster ]]||context=(--context "$KUBE_CONTEXT"); existing_file="$temp/existing"
if "$KUBECTL" "${context[@]}" -n "$OPERATION_NAMESPACE" get secret "$secret" -o 'jsonpath={.immutable}{"\t"}{.data.parameters\.json}' >"$existing_file" 2>/dev/null; then [[ "$(wc -c <"$existing_file")" -le "$MAX_EXISTING_SECRET_RESPONSE_BYTES" ]]||die "existing Secret response is too large"; existing="$(<"$existing_file")"; [[ "${existing%%$'\t'*}" == true && "$(printf %s "${existing#*$'\t'}"|base64 -d|sha256sum|cut -d ' ' -f1)" == "$sha" ]]||die "existing backup parameter Secret drifted"; else "$KUBECTL" "${context[@]}" -n "$OPERATION_NAMESPACE" create secret generic "$secret" --from-file="parameters.json=$params" --dry-run=client -o json|"$JQ" '.immutable=true'|"$KUBECTL" "${context[@]}" -n "$OPERATION_NAMESPACE" create -f - >/dev/null; fi
ctl=(--namespace "$OPERATION_NAMESPACE"); [[ "$KUBE_CONTEXT" == in-cluster ]]||ctl+=(--context "$KUBE_CONTEXT"); "$OPERATIONCTL" "${ctl[@]}" --action submit --name "$name" --operation-id "$name" --requested-by platform:backup --instance "$INSTANCE" --type Backup --parameters-sha256 "$sha" --parameters-secret "$secret" --parameters-key parameters.json --max-attempts 5 >/dev/null
echo "created or verified unapproved Pending Backup ${OPERATION_NAMESPACE}/${name} for request ${REQUEST_ID}"
